"""learn workspace tables

Revision ID: 07df931bf138
Revises: a7b8c9d0e1f2
Create Date: 2026-06-12 02:47:34.663521

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07df931bf138"
down_revision: str | None = "a7b8c9d0e1f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_tn_learn_progress",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.String(length=20), nullable=False),
        sa.Column("xp", sa.Integer(), server_default="0", nullable=False),
        sa.Column("streak", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reviewed_cnt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("correct_cnt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_study_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_learn_progress_user"),
    )
    op.create_table(
        "ai_tn_learn_flashcard",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.String(length=20), nullable=False),
        sa.Column("book_id", sa.String(length=20), nullable=False),
        sa.Column("term", sa.String(length=200), nullable=False),
        sa.Column("meaning", sa.Text(), nullable=False),
        sa.Column("card_type", sa.String(length=30), server_default="단어 카드", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("known_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=20), nullable=False),
        sa.Column("del_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["book_id"], ["ai_tn_book.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_learn_flashcard_book", "ai_tn_learn_flashcard", ["book_id"], unique=False)
    op.create_index(
        "ix_learn_flashcard_user",
        "ai_tn_learn_flashcard",
        ["user_id", "book_id", "del_yn"],
        unique=False,
    )
    op.create_table(
        "ai_tn_learn_session",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.String(length=20), nullable=False),
        sa.Column("book_id", sa.String(length=20), nullable=False),
        sa.Column("session_type", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=20), nullable=False),
        sa.Column("del_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["book_id"], ["ai_tn_book.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "book_id", "session_type", name="uq_learn_session_user_book"
        ),
    )
    op.create_index("ix_learn_session_book", "ai_tn_learn_session", ["book_id"], unique=False)
    op.create_index(
        "ix_learn_session_user", "ai_tn_learn_session", ["user_id", "book_id"], unique=False
    )
    op.create_table(
        "ai_tn_learn_message",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("session_id", sa.String(length=20), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["ai_tn_learn_session.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_learn_message_session",
        "ai_tn_learn_message",
        ["session_id", "created_at"],
        unique=False,
    )

    # ID 채번 시퀀스 (id_generator._SEQ_MAP 매핑)
    op.execute("CREATE SEQUENCE IF NOT EXISTS seq_lses START 1 INCREMENT 1")
    op.execute("CREATE SEQUENCE IF NOT EXISTS seq_lmsg START 1 INCREMENT 1")
    op.execute("CREATE SEQUENCE IF NOT EXISTS seq_lcard START 1 INCREMENT 1")
    op.execute("CREATE SEQUENCE IF NOT EXISTS seq_lprg START 1 INCREMENT 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_learn_message_session", table_name="ai_tn_learn_message")
    op.drop_table("ai_tn_learn_message")
    op.drop_index("ix_learn_session_user", table_name="ai_tn_learn_session")
    op.drop_index("ix_learn_session_book", table_name="ai_tn_learn_session")
    op.drop_table("ai_tn_learn_session")
    op.drop_index("ix_learn_flashcard_user", table_name="ai_tn_learn_flashcard")
    op.drop_index("ix_learn_flashcard_book", table_name="ai_tn_learn_flashcard")
    op.drop_table("ai_tn_learn_flashcard")
    op.drop_table("ai_tn_learn_progress")

    op.execute("DROP SEQUENCE IF EXISTS seq_lses")
    op.execute("DROP SEQUENCE IF EXISTS seq_lmsg")
    op.execute("DROP SEQUENCE IF EXISTS seq_lcard")
    op.execute("DROP SEQUENCE IF EXISTS seq_lprg")
    # ### end Alembic commands ###
