"""sfr108_user_token_device_info

Revision ID: 1227cc541196
Revises: 2227df8fb0d6
Create Date: 2026-04-15 17:06:02.944162

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1227cc541196"
down_revision: str | None = "2227df8fb0d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "com_tn_user_token", sa.Column("user_agent", sa.String(length=500), nullable=True)
    )
    op.add_column("com_tn_user_token", sa.Column("ip_address", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("com_tn_user_token", "ip_address")
    op.drop_column("com_tn_user_token", "user_agent")
    # ### end Alembic commands ###
