"""init_all_tables

Revision ID: 2227df8fb0d6
Revises: 2ca6f26674e3
Create Date: 2026-04-15 15:44:50.653089

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2227df8fb0d6"
down_revision: str | None = "2ca6f26674e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cms_tn_board",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("board_code", sa.String(length=50), nullable=False),
        sa.Column("board_name", sa.String(length=100), nullable=False),
        sa.Column("board_desc", sa.String(length=500), nullable=True),
        sa.Column("board_type", sa.String(length=20), server_default="LIST", nullable=False),
        sa.Column("notice_yn", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("reply_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("comment_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("secret_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("like_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("attach_yn", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("attach_ext", sa.String(length=255), nullable=True),
        sa.Column("attach_size", sa.Integer(), server_default="10240", nullable=False),
        sa.Column("attach_count", sa.Integer(), server_default="5", nullable=False),
        sa.Column("list_count", sa.Integer(), server_default="10", nullable=False),
        sa.Column("auto_reply_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("auto_reply_delay_min", sa.Integer(), server_default="5", nullable=False),
        sa.Column("pipeline_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("use_yn", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=20), nullable=False),
        sa.Column("del_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("board_code"),
        sa.UniqueConstraint("board_code", name="uq_board_code"),
    )
    op.create_index("ix_board_use", "cms_tn_board", ["use_yn", "sort_order"], unique=False)
    op.create_table(
        "com_tn_file",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column(
            "uuid",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("stored_name", sa.String(length=255), nullable=False),
        sa.Column("url_path", sa.String(length=500), nullable=False),
        sa.Column("local_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("file_ext", sa.String(length=20), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("upload_type", sa.String(length=20), nullable=False),
        sa.Column("download_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=20), nullable=False),
        sa.Column("del_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
        sa.UniqueConstraint("uuid", name="ix_file_uuid"),
    )
    op.create_index("ix_file_created", "com_tn_file", ["created_at"], unique=False)
    op.create_index("ix_file_del", "com_tn_file", ["del_yn"], unique=False)
    op.create_table(
        "com_tn_user",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("profile_image_url", sa.String(length=500), nullable=True),
        sa.Column("user_level", sa.Integer(), server_default="10", nullable=False),
        sa.Column("use_yn", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("block_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("blocked_by", sa.String(length=20), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("left_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=20), nullable=False),
        sa.Column("del_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["blocked_by"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_user_del", "com_tn_user", ["del_yn"], unique=False)
    op.create_index("ix_user_left", "com_tn_user", ["left_at"], unique=False)
    op.create_index("ix_user_level", "com_tn_user", ["user_level"], unique=False)
    op.create_table(
        "ai_tn_book",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("owner_user_id", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("book_type", sa.String(length=20), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("total_pages", sa.Integer(), server_default="1", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="PENDING", nullable=False),
        sa.Column("is_favorite", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("share_token", sa.String(length=100), nullable=True),
        sa.Column("summary_text", sa.Text(), nullable=True),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=20), nullable=False),
        sa.Column("del_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["owner_user_id"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("share_token", name="uq_book_share_token"),
    )
    op.create_index(
        "ix_book_owner", "ai_tn_book", ["owner_user_id", "del_yn", "created_at"], unique=False
    )
    op.create_index("ix_book_status", "ai_tn_book", ["status"], unique=False)
    op.create_table(
        "cms_tn_post",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("board_id", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.String(length=20), nullable=False),
        sa.Column("author_name", sa.String(length=100), nullable=False),
        sa.Column("parent_id", sa.String(length=20), nullable=True),
        sa.Column("depth", sa.Integer(), server_default="0", nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("notice_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("secret_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("view_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("like_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("comment_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "auto_reply_status", sa.String(length=20), server_default="PENDING", nullable=False
        ),
        sa.Column("auto_reply_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=20), nullable=False),
        sa.Column("del_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["board_id"], ["cms_tn_board.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["parent_id"], ["cms_tn_post.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_post_auto_reply", "cms_tn_post", ["auto_reply_status", "created_at"], unique=False
    )
    op.create_index(
        "ix_post_board", "cms_tn_post", ["board_id", "del_yn", "created_at"], unique=False
    )
    op.create_index("ix_post_notice", "cms_tn_post", ["board_id", "notice_yn"], unique=False)
    op.create_index("ix_post_parent", "cms_tn_post", ["parent_id"], unique=False)
    op.create_index("ix_post_user", "cms_tn_post", ["user_id"], unique=False)
    op.create_table(
        "com_th_admin_audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("target_id", sa.String(length=20), nullable=True),
        sa.Column("before_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_action", "com_th_admin_audit_log", ["action"], unique=False)
    op.create_index("ix_audit_created", "com_th_admin_audit_log", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_target", "com_th_admin_audit_log", ["target_type", "target_id"], unique=False
    )
    op.create_index("ix_audit_user", "com_th_admin_audit_log", ["user_id"], unique=False)
    op.create_table(
        "com_th_login_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=20), nullable=True),
        sa.Column("login_id", sa.String(length=255), nullable=False),
        sa.Column("login_type", sa.String(length=20), nullable=False),
        sa.Column("login_result", sa.String(length=20), nullable=False),
        sa.Column("fail_reason", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=50), nullable=False),
        sa.Column("client_info", sa.String(length=500), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_login_log_created", "com_th_login_log", ["created_at"], unique=False)
    op.create_index("ix_login_log_result", "com_th_login_log", ["login_result"], unique=False)
    op.create_index("ix_login_log_user", "com_th_login_log", ["user_id"], unique=False)
    op.create_table(
        "com_tn_file_map",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("file_id", sa.String(length=20), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.String(length=20), nullable=False),
        sa.Column("file_group", sa.String(length=50), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=20), nullable=False),
        sa.Column("del_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["file_id"], ["com_tn_file.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_file_map_file", "com_tn_file_map", ["file_id"], unique=False)
    op.create_index(
        "ix_file_map_target", "com_tn_file_map", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "com_tn_user_oauth",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("provider_email", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=20), nullable=False),
        sa.Column("del_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_user_id", name="uq_user_oauth_provider"),
    )
    op.create_index("ix_user_oauth_user", "com_tn_user_oauth", ["user_id"], unique=False)
    op.create_table(
        "com_tn_user_token",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.String(length=20), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["com_tn_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_token_expires", "com_tn_user_token", ["expires_at"], unique=False)
    op.create_index("ix_user_token_hash", "com_tn_user_token", ["token_hash"], unique=False)
    op.create_index("ix_user_token_user", "com_tn_user_token", ["user_id"], unique=False)
    op.create_table(
        "ai_th_pipeline_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("trigger_type", sa.String(length=20), nullable=False),
        sa.Column("triggered_by", sa.String(length=20), nullable=True),
        sa.Column("book_id", sa.String(length=20), nullable=True),
        sa.Column("post_id", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="PENDING", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("total_cnt", sa.Integer(), nullable=True),
        sa.Column("success_cnt", sa.Integer(), nullable=True),
        sa.Column("fail_cnt", sa.Integer(), nullable=True),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.Column("error_stack", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["ai_tn_book.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["post_id"], ["cms_tn_post.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["triggered_by"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pipeline_run_book", "ai_th_pipeline_run", ["book_id"], unique=False)
    op.create_index("ix_pipeline_run_created", "ai_th_pipeline_run", ["created_at"], unique=False)
    op.create_index("ix_pipeline_run_post", "ai_th_pipeline_run", ["post_id"], unique=False)
    op.create_index("ix_pipeline_run_status", "ai_th_pipeline_run", ["status"], unique=False)
    op.create_index("ix_pipeline_run_trigger", "ai_th_pipeline_run", ["trigger_type"], unique=False)
    op.create_table(
        "ai_tn_book_page",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("book_id", sa.String(length=20), nullable=False),
        sa.Column("page_no", sa.Integer(), nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("ocr_engine", sa.String(length=20), nullable=True),
        sa.Column("ocr_confidence", sa.Float(), nullable=True),
        sa.Column("literal_text", sa.Text(), nullable=True),
        sa.Column("interpretive_text", sa.Text(), nullable=True),
        sa.Column("translator_engine", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="PENDING", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=20), nullable=False),
        sa.Column("del_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["book_id"], ["ai_tn_book.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("book_id", "page_no", name="uq_book_page_no"),
    )
    op.create_index("ix_book_page_book", "ai_tn_book_page", ["book_id"], unique=False)
    op.create_table(
        "cms_th_post_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("changed_by", sa.String(length=20), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["changed_by"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["post_id"], ["cms_tn_post.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_post_history_post", "cms_th_post_history", ["post_id", "changed_at"], unique=False
    )
    op.create_table(
        "cms_tn_comment",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("post_id", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.String(length=20), nullable=False),
        sa.Column("author_name", sa.String(length=100), nullable=False),
        sa.Column("parent_id", sa.String(length=20), nullable=True),
        sa.Column("depth", sa.Integer(), server_default="0", nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("like_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_filtered", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("filter_reason", sa.String(length=255), nullable=True),
        sa.Column("filtered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filter_reviewed_by", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=20), nullable=False),
        sa.Column("del_yn", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["filter_reviewed_by"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["parent_id"], ["cms_tn_comment.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["post_id"], ["cms_tn_post.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_comment_filtered", "cms_tn_comment", ["is_filtered"], unique=False)
    op.create_index("ix_comment_parent", "cms_tn_comment", ["parent_id"], unique=False)
    op.create_index(
        "ix_comment_post", "cms_tn_comment", ["post_id", "del_yn", "created_at"], unique=False
    )
    op.create_index("ix_comment_user", "cms_tn_comment", ["user_id"], unique=False)
    op.create_table(
        "ai_th_page_revision",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("page_id", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("literal_text", sa.Text(), nullable=False),
        sa.Column("interpretive_text", sa.Text(), nullable=False),
        sa.Column("edited_by", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["edited_by"], ["com_tn_user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["page_id"], ["ai_tn_book_page.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_page_revision_page", "ai_th_page_revision", ["page_id", "version"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_page_revision_page", table_name="ai_th_page_revision")
    op.drop_table("ai_th_page_revision")
    op.drop_index("ix_comment_user", table_name="cms_tn_comment")
    op.drop_index("ix_comment_post", table_name="cms_tn_comment")
    op.drop_index("ix_comment_parent", table_name="cms_tn_comment")
    op.drop_index("ix_comment_filtered", table_name="cms_tn_comment")
    op.drop_table("cms_tn_comment")
    op.drop_index("ix_post_history_post", table_name="cms_th_post_history")
    op.drop_table("cms_th_post_history")
    op.drop_index("ix_book_page_book", table_name="ai_tn_book_page")
    op.drop_table("ai_tn_book_page")
    op.drop_index("ix_pipeline_run_trigger", table_name="ai_th_pipeline_run")
    op.drop_index("ix_pipeline_run_status", table_name="ai_th_pipeline_run")
    op.drop_index("ix_pipeline_run_post", table_name="ai_th_pipeline_run")
    op.drop_index("ix_pipeline_run_created", table_name="ai_th_pipeline_run")
    op.drop_index("ix_pipeline_run_book", table_name="ai_th_pipeline_run")
    op.drop_table("ai_th_pipeline_run")
    op.drop_index("ix_user_token_user", table_name="com_tn_user_token")
    op.drop_index("ix_user_token_hash", table_name="com_tn_user_token")
    op.drop_index("ix_user_token_expires", table_name="com_tn_user_token")
    op.drop_table("com_tn_user_token")
    op.drop_index("ix_user_oauth_user", table_name="com_tn_user_oauth")
    op.drop_table("com_tn_user_oauth")
    op.drop_index("ix_file_map_target", table_name="com_tn_file_map")
    op.drop_index("ix_file_map_file", table_name="com_tn_file_map")
    op.drop_table("com_tn_file_map")
    op.drop_index("ix_login_log_user", table_name="com_th_login_log")
    op.drop_index("ix_login_log_result", table_name="com_th_login_log")
    op.drop_index("ix_login_log_created", table_name="com_th_login_log")
    op.drop_table("com_th_login_log")
    op.drop_index("ix_audit_user", table_name="com_th_admin_audit_log")
    op.drop_index("ix_audit_target", table_name="com_th_admin_audit_log")
    op.drop_index("ix_audit_created", table_name="com_th_admin_audit_log")
    op.drop_index("ix_audit_action", table_name="com_th_admin_audit_log")
    op.drop_table("com_th_admin_audit_log")
    op.drop_index("ix_post_user", table_name="cms_tn_post")
    op.drop_index("ix_post_parent", table_name="cms_tn_post")
    op.drop_index("ix_post_notice", table_name="cms_tn_post")
    op.drop_index("ix_post_board", table_name="cms_tn_post")
    op.drop_index("ix_post_auto_reply", table_name="cms_tn_post")
    op.drop_table("cms_tn_post")
    op.drop_index("ix_book_status", table_name="ai_tn_book")
    op.drop_index("ix_book_owner", table_name="ai_tn_book")
    op.drop_table("ai_tn_book")
    op.drop_index("ix_user_level", table_name="com_tn_user")
    op.drop_index("ix_user_left", table_name="com_tn_user")
    op.drop_index("ix_user_del", table_name="com_tn_user")
    op.drop_table("com_tn_user")
    op.drop_index("ix_file_del", table_name="com_tn_file")
    op.drop_index("ix_file_created", table_name="com_tn_file")
    op.drop_table("com_tn_file")
    op.drop_index("ix_board_use", table_name="cms_tn_board")
    op.drop_table("cms_tn_board")
    # ### end Alembic commands ###
