"""init

Revision ID: 2ca6f26674e3
Revises:
Create Date: 2026-04-15 11:20:17.305197

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2ca6f26674e3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
