"""translate_ocr_redesign

Revision ID: 57a14d596e9a
Revises: d3e4f5a6b7c8
Create Date: 2026-05-24 18:34:12.104404

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57a14d596e9a"
down_revision: str | None = "d3e4f5a6b7c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ai_th_page_revision", sa.Column("ocr_text", sa.Text(), nullable=True))
    op.create_unique_constraint(
        "uq_page_revision_version", "ai_th_page_revision", ["page_id", "version"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_page_revision_version", "ai_th_page_revision", type_="unique")
    op.drop_column("ai_th_page_revision", "ocr_text")
    # ### end Alembic commands ###
