"""sfr206_book_bookmark

Revision ID: d760d31a9579
Revises: 31233b1255cb
Create Date: 2026-05-29 14:45:13.974498

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d760d31a9579"
down_revision: str | None = "31233b1255cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_tn_book_bookmark",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=20), nullable=False),
        sa.Column("book_id", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["ai_tn_book.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["com_tn_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "book_id", name="uq_book_bookmark_user_book"),
    )
    op.create_index("ix_book_bookmark_user", "ai_tn_book_bookmark", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_book_bookmark_user", table_name="ai_tn_book_bookmark")
    op.drop_table("ai_tn_book_bookmark")
    # ### end Alembic commands ###
