"""add source_file_id to book

Revision ID: d80be6b751d2
Revises: 55b08d8db828
Create Date: 2026-05-15 14:23:49.432419

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d80be6b751d2"
down_revision: str | None = "55b08d8db828"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ai_tn_book", sa.Column("source_file_id", sa.String(length=20), nullable=True))
    op.create_foreign_key(
        None, "ai_tn_book", "com_tn_file", ["source_file_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # upgrade()에서 이름 없이 생성한 FK의 PostgreSQL 자동 생성 이름
    op.drop_constraint("ai_tn_book_source_file_id_fkey", "ai_tn_book", type_="foreignkey")
    op.drop_column("ai_tn_book", "source_file_id")
    # ### end Alembic commands ###
