export const API_ENDPOINTS = {
    ME: '/api/v1/users/me',
    AUTH_REFRESH: '/auth/refresh',
    AUTH_LOGOUT: '/auth/logout',
    BOARDS_LIST: '/api/v1/boards/list',
    BOARD_CATEGORIES: (boardCode: string) => `/api/v1/boards/${boardCode}/categories`,
    POSTS: '/api/v1/posts',
    POSTS_LIST: '/api/v1/posts/list',
    POST: (id: string) => `/api/v1/posts/${id}`,
    POST_COMMENTS_LIST: (id: string) => `/api/v1/posts/${id}/comments/list`,
    POST_COMMENTS: (id: string) => `/api/v1/posts/${id}/comments`,
    UPLOADS: '/api/v1/uploads',
    BOARD_UPLOADS: (boardCode: string) => `/api/v1/boards/${boardCode}/uploads`,
    TRANSLATE: '/api/v1/translate',
    TRANSLATE_OCR: '/api/v1/translate/ocr',
    TRANSLATE_TEXT: '/api/v1/translate/text',
    TRANSLATE_TITLE_UPDATE: (bookId: string) => `/api/v1/translate/${bookId}`,
    TRANSLATE_PAGE_EDIT: (bookId: string, pageNo: number) => `/api/v1/translate/${bookId}/pages/${pageNo}`,
    TRANSLATE_MINE: '/api/v1/translate/mine',
    TRANSLATE_LIST: '/api/v1/translate/list',
    TRANSLATE_DETAIL: (id: string) => `/api/v1/translate/${id}`,
    TRANSLATE_RETRY: (id: string) => `/api/v1/translate/${id}/retry`,
    TRANSLATE_PUBLIC_LIST: '/api/v1/translate/public/list',
    TRANSLATE_PUBLIC_DETAIL: (id: string) => `/api/v1/translate/public/${id}`,
    TRANSLATE_FAVORITE: (bookId: string) => `/api/v1/translate/${bookId}/favorite`,
    TRANSLATE_BOOKMARK: (bookId: string) => `/api/v1/translate/public/${bookId}/bookmark`,
    LEARN_WORKSPACE: (bookId: string) => `/api/v1/learn/books/${bookId}`,
    LEARN_CHAT: (bookId: string) => `/api/v1/learn/books/${bookId}/chat`,
    LEARN_TUTOR: (bookId: string) => `/api/v1/learn/books/${bookId}/tutor`,
    LEARN_SUMMARY: (bookId: string) => `/api/v1/learn/books/${bookId}/summary`,
    LEARN_FLASHCARDS: (bookId: string) => `/api/v1/learn/books/${bookId}/flashcards`,
    LEARN_FLASHCARD_REVIEW: (bookId: string) => `/api/v1/learn/books/${bookId}/flashcards/review`,
    LEARN_QUIZ: (bookId: string) => `/api/v1/learn/books/${bookId}/quiz`,
} as const;
